name: Sphinx

on:
  release:
    types:
      - published

jobs:
  documentation:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    # note (crcrpar): `readthedocs/build:latest` seems to use Python3.8.
    # Optuna uses that image in CircleCI documentation build,
    # so we can use Python3.7 here for the backward compatibility
    # of Pickle's protocol version (Python3.8's pickle's default protocol version
    # is not compatible completely with Python3.7 and Python3.6).
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    # note (crcrpar): We've not updated tutorial frequently enough so far thus
    # it'd be okay to discard cache by any small changes including typo fix under tutorial directory.
    - name: Sphinx Gallery Cache
      uses: actions/cache@v2
      env:
        cache-name: sphx-glry-documentation
      with:
        path: |
          tutorial/MNIST
          docs/source/tutorial
        key: py3.7-${{ env.cache-name }}-${{ hashFiles('tutorial/**/*') }}

    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install --progress-bar off -U .[document]

    - name: Build Document
      run: |
        cd docs
        make html
        cd ../

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      env:
        REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
        destination_dir: ${{ github.event.release.tag_name }}
